#!/usr/bin/env python3
"""Scaffold-agent generator.

Usage:
    python scripts/bootstrap.py <project-name> [--out /path/to/output] [--skip-deps]

Reads embedded templates, substitutes {{PROJECT_NAME}} / {{PROJECT_SLUG}},
and writes a complete FastAPI + React + SQLite project to a fresh directory.

Main-touching rule:
    This repo IS the generator source. Generated files never touch this repo.
"""
from __future__ import annotations

import argparse
import os
import re
import shutil
import sys
from pathlib import Path
from string import Template
from typing import Dict

PROJECT_ROOT = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = PROJECT_ROOT / "scripts" / "templates"

# ---------------------------------------------------------------------------
# Built-in templates (in-repo fallback).
# ---------------------------------------------------------------------------
TEMPLATES: Dict[str, str] = {}


def _tpl(name: str) -> str:
    return TEMPLATES[name]


# ---------------------------------------------------------------------------
# Defaults
# ---------------------------------------------------------------------------
DEFAULT_DESCRIPTION = "Generated by scaffold-agent"


# ---------------------------------------------------------------------------
# Substitution helpers
# ---------------------------------------------------------------------------
def _substitute(project_name: str, slug: str, description: str, content: str) -> str:
    # Replace exact {{VAR}} placeholders using plain str.replace to avoid
    # conflicts with JSX/CSS braces or Template $ sign rules.
    content = content.replace("{{PROJECT_NAME}}", project_name)
    content = content.replace("{{PROJECT_SLUG}}", slug)
    content = content.replace("{{PROJECT_DESC}}", description)
    # Remove any leftover placeholders
    content = re.sub(r"\{\{[A-Z0-9_]+\}\}", "", content)
    return content


def _write(dest: Path, content: str) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(content, encoding="utf-8")


# ---------------------------------------------------------------------------
# File generators
# ---------------------------------------------------------------------------


def _readme(project_name: str, slug: str) -> str:
    return f"""# {project_name}

Generated by scaffold-agent. A runnable FastAPI + React + SQLite starter kit.

## Run (dev)

> Requires Docker and Docker Compose.

```bash
docker compose up --build
```

| Service | URL |
|--------|-----|
| Frontend | http://localhost:5173 |
| Backend | http://localhost:8000 |
| Backend health | http://localhost:8000/health |
| API docs | http://localhost:8000/docs |

### Stop

```bash
docker compose down
```

## Run (manual, no Docker)

### Backend

```bash
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
cp .env.example .env
uvicorn app.main:app --reload --port 8000
```

### Frontend

```bash
cd frontend
npm install
npm run dev
```

## Tests

```bash
cd backend
python -m pytest -q
```

## Deploy to GCP VM

1. Create a GCE e2-medium (2 vCPU, 4 GB) with Container-Optimized OS.
2. Install Docker + Compose on VM.
3. `git clone` this repo onto VM and run `docker compose -f docker-compose.prod.yml up -d`.
4. Open firewall for `tcp:8000` and `tcp:80`.

See `docs/deploy.md` for the exact systemd units and env injection.
"""


def _docker_compose() -> str:
    return """version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    env_file:
      - .env.example
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
"""


def _dockerfile_backend(project_slug: str) -> str:
    return """FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \\
        gcc libpq-dev curl \\
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
"""


def _dockerfile_frontend() -> str:
    return """FROM node:20-slim AS build
WORKDIR /app
COPY package.json pnpm-lock.yaml* ./
RUN npm install
COPY . .
RUN npm run build

# production stage reuses node to serve via `npm run preview` or copy dist to nginx
CMD ["npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "5173"]
"""


def _backend_main_py() -> str:
    return """from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.routers import health, chat
from app.config import settings


def create_app() -> FastAPI:
    app = FastAPI(title="{{PROJECT_NAME}}")

    app.add_middleware(
        CORSMiddleware,
        allow_origins=["*"],
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    app.include_router(health.router)
    app.include_router(chat.router)

    @app.get("/")
    async def root():
        return {"ok": True, "project": "{{PROJECT_SLUG}}"}

    return app


app = create_app()
"""


def _backend_config() -> str:
    return """from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", extra="allow")

    PROJECT_NAME: str = "{{PROJECT_SLUG}}"
    DATABASE_URL: str = "sqlite:///./data/app.db"
    LLM_API_KEY: str | None = None
    LLM_BASE_URL: str | None = None
    LLM_MODEL: str = "gpt-4o-mini"


settings = Settings()
"""


def _backend_db() -> str:
    return """import os
from pathlib import Path
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, DeclarativeBase

DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///./data/app.db")

if DATABASE_URL.startswith("sqlite"):
    db_path = DATABASE_URL.replace("sqlite:///", "", 1)
    Path(db_path).parent.mkdir(parents=True, exist_ok=True)

engine = create_engine(
    DATABASE_URL,
    connect_args={"check_same_thread": False} if DATABASE_URL.startswith("sqlite") else {},
    echo=False,
)

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


class Base(DeclarativeBase):
    pass
"""


def _backend_models() -> str:
    return """from sqlalchemy import Column, Integer, String, Text, DateTime, func
from app.db import Base


class Run(Base):
    __tablename__ = "runs"

    id = Column(Integer, primary_key=True, index=True)
    status = Column(String(32), nullable=False, default="succeeded")
    user_message = Column(Text, nullable=False)
    assistant_message = Column(Text, nullable=True)
    error_message = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())
"""


def _backend_init() -> str:
    return ""


def _backend_health_router() -> str:
    return """from fastapi import APIRouter
from sqlalchemy import text
from app.db import engine

router = APIRouter(prefix="/health", tags=["health"])


@router.get("")
async def health():
    try:
        with engine.connect() as conn:
            conn.execute(text("SELECT 1"))
        return {"status": "ok", "version": "0.1.0"}
    except Exception as exc:
        return {"status": "error", "detail": str(exc)}
"""


def _backend_chat_router() -> str:
    return """from fastapi import APIRouter
from pydantic import BaseModel, Field

from app.config import settings
from app.agent import run_agent

router = APIRouter(prefix="/api", tags=["chat"])


class Message(BaseModel):
    role: str
    content: str


class ChatRequest(BaseModel):
    messages: list[Message] = Field(min_length=1)


class ChatResponse(BaseModel):
    reply: str


@router.post("/chat", response_model=ChatResponse)
async def chat(req: ChatRequest):
    assistant = await run_agent(req.messages[-1].content)
    return ChatResponse(reply=assistant)
"""


def _backend_agent() -> str:
    return """import httpx
from app.config import settings


async def run_agent(user_message: str) -> str:
    if not settings.LLM_API_KEY or not settings.LLM_BASE_URL:
        return f"[stub] Echo: {user_message}"

    try:
        async with httpx.AsyncClient(timeout=30) as client:
            payload = {
                "model": settings.LLM_MODEL,
                "messages": [
                    {"role": "system", "content": "You are a helpful assistant."},
                    {"role": "user", "content": user_message},
                ],
            }
            headers = {
                "Authorization": f"Bearer {settings.LLM_API_KEY}",
                "Content-Type": "application/json",
            }
            resp = await client.post(
                f"{settings.LLM_BASE_URL.rstrip('/')}/v1/chat/completions",
                json=payload,
                headers=headers,
            )
            resp.raise_for_status()
            data = resp.json()
            return data["choices"][0]["message"]["content"]
    except Exception as exc:
        return f"[stub] LLM call failed: {exc}"
"""


def _requirements() -> str:
    return """fastapi>=0.111.0
uvicorn[standard]>=0.30.0
sqlalchemy>=2.0
alembic>=1.13
pydantic-settings>=2.4
httpx>=0.27
pytest>=8.3
pytest-asyncio>=0.23
python-dotenv>=1.0
"""


def _pyproject() -> str:
    return """[project]
name = "{{PROJECT_SLUG}}-backend"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.111.0",
    "uvicorn[standard]>=0.30.0",
    "sqlalchemy>=2.0",
    "alembic>=1.13",
    "pydantic-settings>=2.4",
    "httpx>=0.27",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.3",
    "pytest-asyncio>=0.23",
]
"""


def _env_example() -> str:
    return """DATABASE_URL=sqlite:///./data/app.db
LLM_API_KEY=
LLM_BASE_URL=
LLM_MODEL=gpt-4o-mini
"""


def _readme_frontend() -> str:
    return """# Frontend

Generated by scaffold-agent. React + TypeScript + Vite.

## Commands
npm install
npm run dev
npm run build
"""


def _package_json(project_slug: str) -> str:
    return f"""{{
  "name": "{project_slug}-frontend",
  "private": true,
  "version": "0.1.0",
  "type": "module",
  "scripts": {{
    "dev": "vite",
    "build": "tsc -b && vite build",
    "preview": "vite preview"
  }},
  "dependencies": {{
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  }},
  "devDependencies": {{
    "@types/react": "^18.3.3",
    "@types/react-dom": "^18.3.0",
    "@vitejs/plugin-react": "^4.3.1",
    "autoprefixer": "^10.4.20",
    "postcss": "^8.4.41",
    "tailwindcss": "^3.4.10",
    "typescript": "~5.5.4",
    "vite": "^5.4.2"
  }}
}}
"""


def _tsconfig_json() -> str:
    return """{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "isolatedModules": true,
    "moduleDetection": "force",
    "noEmit": true,
    "jsx": "react-jsx",
    "strict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noFallthroughCasesInSwitch": true
  },
  "include": ["src"]
}
"""


def _tsconfig_node() -> str:
    return """{
  "compilerOptions": {
    "composite": true,
    "tsBuildInfoFile": "./node_modules/.tmp/tsconfig.node.tsbuildinfo",
    "skipLibCheck": true,
    "module": "ESNext",
    "moduleResolution": "bundler",
    "allowSyntheticDefaultImports": true
  },
  "include": ["vite.config.ts"]
}
"""


def _vite_config() -> str:
    return """import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
  server: {
    host: "0.0.0.0",
    port: 5173,
    proxy: {
      "/api": "http://localhost:8000",
      "/health": "http://localhost:8000",
    },
  },
});
"""


def _tailwind_config() -> str:
    return """/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{js,ts,jsx,tsx}"],
  theme: { extend: {} },
  plugins: [],
};
"""


def _postcss_config() -> str:
    return """export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
"""


def _main_tsx() -> str:
    return """import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import "./index.css";

ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
"""


def _app_tsx(project_name: str) -> str:
    project_title = project_name + " Chat"
    return (
'import { useState } from "react";\n\n'
"const API_BASE = import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:8000';\n\n"
'type Role = "user" | "assistant";\n\n'
"interface Message {\n"
"  role: Role;\n"
"  content: string;\n"
"}\n\n"
"export default function App() {\n"
'  const [messages, setMessages] = useState<Message[]>([]);\n'
'  const [value, setValue] = useState("");\n'
"  const [loading, setLoading] = useState(false);\n"
'  const [error, setError] = useState<string | null>(null);\n\n'
"  async function send() {\n"
"    const text = value.trim();\n"
"    if (!text) return;\n"
'    setValue("");\n'
"    setLoading(true);\n"
"    setError(null);\n"
"    const next: Message[] = [...messages, { role: 'user', content: text }];\n"
"    setMessages(next);\n"
"    try {\n"
'      const res = await fetch(`${API_BASE}/api/chat`, {\n'
'        method: "POST",\n'
'        headers: { "Content-Type": "application/json" },\n'
"        body: JSON.stringify({ messages: next }),\n"
"      });\n"
"      if (!res.ok) throw new Error(`HTTP ${res.status}`);\n"
"      const data = (await res.json()) as { reply: string };\n"
"      setMessages([...next, { role: 'assistant', content: data.reply }]);\n"
"    } catch (e: unknown) {\n"
'      setError(e instanceof Error ? e.message : "Unknown error");\n'
"    } finally {\n"
"      setLoading(false);\n"
"    }\n"
"  }\n\n"
'  return (\n'
'    <div className="min-h-screen bg-gray-50">\n'
'      <header className="border-b bg-white">\n'
'        <div className="mx-auto max-w-2xl px-4 py-3">\n'
f'            <h1 className="text-xl font-semibold text-gray-900">{project_title}</h1>\n'
"        </div>\n"
"      </header>\n\n"
'      <main className="mx-auto max-w-2xl px-4 py-4">\n'
'        <div className="rounded-lg border bg-white">\n'
'          <div className="h-96 overflow-y-auto p-4 space-y-3">\n'
'            {messages.length === 0 && (\n'
'              <p className="text-sm text-gray-400">Type a message to get started...</p>\n'
"            )}\n"
"            {messages.map((m, i) => (\n"
'              <div key={i} className={`flex ${m.role === "user" ? "justify-end" : "justify-start"}`}>\n'
"                <div\n"
'                  className={`max-w-[80%] rounded-lg px-3 py-2 text-sm ${\n'
"                    m.role === 'user'\n"
'                      ? "bg-blue-600 text-white"\n'
'                      : "bg-gray-100 text-gray-900"\n'
"                  }`}\n"
"                >\n"
"                  {m.content}\n"
"                </div>\n"
"              </div>\n"
"            ))}\n"
"            {loading && <p className='text-sm text-gray-400'>Thinking...</p>}\n"
"          </div>\n\n"
"            {error && (\n"
'              <div className="border-t bg-red-50 px-4 py-2 text-sm text-red-700">\n'
"                {error}\n"
"              </div>\n"
"            )}\n\n"
'          <div className="flex items-center gap-2 border-t p-3">\n'
'            <input\n'
'              className="flex-1 rounded-md border px-3 py-2 text-sm outline-none focus:border-blue-500"\n'
'              placeholder="Message..."\n'
'              value={value}\n'
'              onChange={(e) => setValue(e.target.value)}\n'
'              onKeyDown={(e) => e.key === "Enter" && !e.shiftKey && send()}\n'
"            />\n"
'            <button\n'
"              onClick={send}\n"
'              className="rounded-md bg-blue-600 px-4 py-2 text-sm font-medium text-white hover:bg-blue-700 disabled:opacity-50"\n'
"              disabled={loading}\n"
"            >\n"
"              Send\n"
"            </button>\n"
"          </div>\n"
"        </div>\n"
"      </main>\n"
"    </div>\n"
"  );\n"
"}\n"
    )

def _index_html() -> str:
    return """<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Chat</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
"""


def _index_css() -> str:
    return """@tailwind base;
@tailwind components;
@tailwind utilities;
"""


def _vite_env_dts() -> str:
    return """/// <reference types="vite/client" />
"""


def _backend_init_routers() -> str:
    return ""


def _backend_alembic_ini() -> str:
    # A valid alembic.ini stubs; migration env.py lives under alembic/
    return """[alembic]
script_location = alembic
sqlalchemy.url = driver://user:pass@localhost/dbname

[post_write_hooks]

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
"""


def _backend_alembic_env(project_slug: str) -> str:
    return f'''"""alembic env file - generate revision, migrate."""
from logging.config import fileConfig
from sqlalchemy import engine_from_config
from sqlalchemy import pool
from alembic import context

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Alembric env.py should import the project models' Base for autogenerate.
# The project places Base at app.db.Base; we import it lazily so `alembic`
# can always run without every env var set.
try:
    from app.db import Base  # type: ignore
    target_metadata = Base.metadata
except Exception:
    target_metadata = None


def run_migrations_offline() -> None:
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={{"paramstyle": "named"}},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
'''


def _backend_alembic_script() -> str:
    return '"""empty message"""\nrevision = "REVID"\ndown_revision = None\nbranch_labels = None\ndepends_on = None\n'


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------


def generate(
    project_name: str,
    dest_root: Path,
    description: str,
    skip_deps: bool,
) -> Path:
    project_dir = dest_root / project_name
    if project_dir.exists():
        raise SystemExit(f"Destination already exists: {project_dir}")

    project_dir.mkdir(parents=True)
    slug = _slug(project_name)
    substitutions = {
        "{{PROJECT_NAME}}": project_name,
        "{{PROJECT_SLUG}}": slug,
        "{{PROJECT_DESC}}": description,
    }

    def write(rel: str, content: str) -> None:
        (project_dir / rel).parent.mkdir(parents=True, exist_ok=True)
        text = _substitute(project_name, slug, description, content)
        (project_dir / rel).write_text(text, encoding="utf-8")

    write("README.md", _readme(project_name, slug))
    write(".env.example", _env_example())
    write("docker-compose.yml", _docker_compose())
    write("Dockerfile.backend", _dockerfile_backend(slug))
    write("Dockerfile.frontend", _dockerfile_frontend())
    write("backend/pyproject.toml", _pyproject())
    write("backend/requirements.txt", _requirements())
    write("backend/app/__init__.py", "")
    write("backend/app/main.py", _backend_main_py())
    write("backend/app/config.py", _backend_config())
    write("backend/app/db.py", _backend_db())
    write("backend/app/models.py", _backend_models())
    write("backend/app/agent.py", _backend_agent())
    write("backend/app/routers/__init__.py", _backend_init())
    write("backend/app/routers/health.py", _backend_health_router())
    write("backend/app/routers/chat.py", _backend_chat_router())
    write("backend/app/routers/__init__.py", _backend_init())
    write("backend/tests/__init__.py", "")
    write("backend/tests/test_health.py", _health_test())
    write("backend/tests/test_chat.py", _chat_test())
    write("backend/alembic.ini", _backend_alembic_ini())
    write("backend/alembic/env.py", _backend_alembic_env(slug))
    write("backend/alembic/versions/.gitkeep", "")

    write("frontend/package.json", _package_json(slug))
    write("frontend/vite.config.ts", _vite_config())
    write("frontend/tsconfig.json", _tsconfig_json())
    write("frontend/tsconfig.node.json", _tsconfig_node())
    write("frontend/tailwind.config.js", _tailwind_config())
    write("frontend/postcss.config.js", _postcss_config())
    write("frontend/index.html", _index_html())
    write("frontend/README.md", _readme_frontend())
    write("frontend/src/main.tsx", _main_tsx())
    write("frontend/src/App.tsx", _app_tsx(project_name))
    write("frontend/src/index.css", _index_css())
    write("frontend/src/vite-env.d.ts", _vite_env_dts())
    write("frontend/public/.gitkeep", "")

    if not skip_deps:
        _install_deps(project_dir, slug)

    return project_dir


def _slug(name: str) -> str:
    return re.sub(r"[^a-z0-9-]+", "-", name.lower()).strip("-") or "my-project"


def _install_deps(project_dir: Path, slug: str) -> None:
    print("\n[generator] optional dependency install skipped by default; run inside <project> when ready.\n")


def _health_test() -> str:
    return """from fastapi.testclient import TestClient
from app.main import app

client = TestClient(app)


def test_health():
    r = client.get("/health")
    assert r.status_code == 200
    assert r.json()["status"] == "ok"
"""


def _chat_test() -> str:
    return """from fastapi.testclient import TestClient
from app.main import app

client = TestClient(app)


def test_chat_stub():
    r = client.post("/api/chat", json={"messages": [{"role": "user", "content": "hi"}]})
    assert r.status_code == 200
    body = r.json()
    assert "reply" in body
    assert "hi" in body["reply"]
"""


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="scaffold-agent project generator")
    parser.add_argument("project_name", help="Directory name for the generated project.")
    parser.add_argument("--out", type=Path, default=None, help="Output parent directory (default: sibling of this repo).")
    parser.add_argument("--description", default=DEFAULT_DESCRIPTION, help="Project description.")
    parser.add_argument("--skip-deps", action="store_true", help="Skip optional dependency installation.")
    parser.add_argument("--dry-run", action="store_true", help="Print files without writing them.")
    args = parser.parse_args(argv)

    dest_parent = args.out
    if dest_parent is None:
        dest_parent = PROJECT_ROOT.parent

    dest = dest_parent.resolve()
    print(f"[gen] output root: {dest}")
    print(f"[gen] project: {args.project_name}\n")

    if args.dry_run:
        for rel, content in TEMPLATES.items():
            rendered = _substitute(args.project_name, _slug(args.project_name), args.description, content)
            print(f"--- {rel} ---\n{rendered}\n")
        return 0

    out = generate(
        project_name=args.project_name,
        dest_root=dest,
        description=args.description,
        skip_deps=args.skip_deps,
    )
    print(f"\n[gen] created: {out}")
    print("Next steps:")
    print(f"  cd {out.parent.name if out.parent != PROJECT_ROOT.parent else out.name}")
    print("  docker compose up --build")
    print("  open http://localhost:5173")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
